export const WORKER_REPOSITORY = 'WORKER_REPOSITORY';
export const WORKER_EVENT_EMITTER = 'WORKER_EVENT_EMITTER';

export const AUTH_GATEWAY = 'AUTH_GATEWAY';

export const SUPABASE_CLIENT = 'SUPABASE_CLIENT';
