name: Deploy Supabase Function
on:
  workflow_run:
    workflows:
      - "Deploy to Railway"
    branches: 
      - "main"
    types:
      - requested

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: keugddzbvqmrtxzeduin

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase functions deploy signup --project-ref $PROJECT_ID