name: Migrate Database
on:
  workflow_run:
    workflows:
      - "Run Tests"
    branches: 
      - "main"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Migrate Database
        run: npm run migrate:prod
